// Generated by gencpp from file sensors/gpgga.msg
// DO NOT EDIT!


#ifndef SENSORS_MESSAGE_GPGGA_H
#define SENSORS_MESSAGE_GPGGA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sensors
{
template <class ContainerAllocator>
struct gpgga_
{
  typedef gpgga_<ContainerAllocator> Type;

  gpgga_()
    : header()
    , gga_1()
    , utc_time_2()
    , lat_3(0.0)
    , latdir_4()
    , lon_5(0.0)
    , londir_6()
    , QF_7()
    , satNo_8(0.0)
    , hdop_9(0.0)
    , alt_10(0.0)
    , units_11()
    , age_14()
    , mode_15()
    , initdata_0()  {
    }
  gpgga_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gga_1(_alloc)
    , utc_time_2(_alloc)
    , lat_3(0.0)
    , latdir_4(_alloc)
    , lon_5(0.0)
    , londir_6(_alloc)
    , QF_7(_alloc)
    , satNo_8(0.0)
    , hdop_9(0.0)
    , alt_10(0.0)
    , units_11(_alloc)
    , age_14(_alloc)
    , mode_15(_alloc)
    , initdata_0(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _gga_1_type;
  _gga_1_type gga_1;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _utc_time_2_type;
  _utc_time_2_type utc_time_2;

   typedef float _lat_3_type;
  _lat_3_type lat_3;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _latdir_4_type;
  _latdir_4_type latdir_4;

   typedef float _lon_5_type;
  _lon_5_type lon_5;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _londir_6_type;
  _londir_6_type londir_6;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _QF_7_type;
  _QF_7_type QF_7;

   typedef float _satNo_8_type;
  _satNo_8_type satNo_8;

   typedef float _hdop_9_type;
  _hdop_9_type hdop_9;

   typedef float _alt_10_type;
  _alt_10_type alt_10;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _units_11_type;
  _units_11_type units_11;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _age_14_type;
  _age_14_type age_14;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_15_type;
  _mode_15_type mode_15;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _initdata_0_type;
  _initdata_0_type initdata_0;




  typedef boost::shared_ptr< ::sensors::gpgga_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensors::gpgga_<ContainerAllocator> const> ConstPtr;

}; // struct gpgga_

typedef ::sensors::gpgga_<std::allocator<void> > gpgga;

typedef boost::shared_ptr< ::sensors::gpgga > gpggaPtr;
typedef boost::shared_ptr< ::sensors::gpgga const> gpggaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensors::gpgga_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensors::gpgga_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensors': ['/home/galaxy/Pictures/rs_pro/src/RS_Localization/sensors/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensors::gpgga_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensors::gpgga_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::gpgga_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::gpgga_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::gpgga_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::gpgga_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensors::gpgga_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4737bb13c293b1a6e412f6cf424cb5e1";
  }

  static const char* value(const ::sensors::gpgga_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4737bb13c293b1a6ULL;
  static const uint64_t static_value2 = 0xe412f6cf424cb5e1ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensors::gpgga_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensors/gpgga";
  }

  static const char* value(const ::sensors::gpgga_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensors::gpgga_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string gga_1\n\
string utc_time_2\n\
float32 lat_3\n\
string  latdir_4\n\
float32 lon_5\n\
string  londir_6\n\
string  QF_7\n\
float32 satNo_8\n\
float32 hdop_9\n\
float32 alt_10\n\
string units_11\n\
string age_14\n\
string mode_15\n\
string initdata_0\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::sensors::gpgga_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensors::gpgga_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gga_1);
      stream.next(m.utc_time_2);
      stream.next(m.lat_3);
      stream.next(m.latdir_4);
      stream.next(m.lon_5);
      stream.next(m.londir_6);
      stream.next(m.QF_7);
      stream.next(m.satNo_8);
      stream.next(m.hdop_9);
      stream.next(m.alt_10);
      stream.next(m.units_11);
      stream.next(m.age_14);
      stream.next(m.mode_15);
      stream.next(m.initdata_0);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gpgga_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensors::gpgga_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensors::gpgga_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gga_1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.gga_1);
    s << indent << "utc_time_2: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.utc_time_2);
    s << indent << "lat_3: ";
    Printer<float>::stream(s, indent + "  ", v.lat_3);
    s << indent << "latdir_4: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.latdir_4);
    s << indent << "lon_5: ";
    Printer<float>::stream(s, indent + "  ", v.lon_5);
    s << indent << "londir_6: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.londir_6);
    s << indent << "QF_7: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.QF_7);
    s << indent << "satNo_8: ";
    Printer<float>::stream(s, indent + "  ", v.satNo_8);
    s << indent << "hdop_9: ";
    Printer<float>::stream(s, indent + "  ", v.hdop_9);
    s << indent << "alt_10: ";
    Printer<float>::stream(s, indent + "  ", v.alt_10);
    s << indent << "units_11: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.units_11);
    s << indent << "age_14: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.age_14);
    s << indent << "mode_15: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode_15);
    s << indent << "initdata_0: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.initdata_0);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSORS_MESSAGE_GPGGA_H
