// Generated by gencpp from file sensors/encoders.msg
// DO NOT EDIT!


#ifndef SENSORS_MESSAGE_ENCODERS_H
#define SENSORS_MESSAGE_ENCODERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sensors
{
template <class ContainerAllocator>
struct encoders_
{
  typedef encoders_<ContainerAllocator> Type;

  encoders_()
    : header()
    , lfront(0.0)
    , lrear(0.0)
    , rfront(0.0)
    , rrear(0.0)  {
    }
  encoders_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lfront(0.0)
    , lrear(0.0)
    , rfront(0.0)
    , rrear(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _lfront_type;
  _lfront_type lfront;

   typedef float _lrear_type;
  _lrear_type lrear;

   typedef float _rfront_type;
  _rfront_type rfront;

   typedef float _rrear_type;
  _rrear_type rrear;




  typedef boost::shared_ptr< ::sensors::encoders_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensors::encoders_<ContainerAllocator> const> ConstPtr;

}; // struct encoders_

typedef ::sensors::encoders_<std::allocator<void> > encoders;

typedef boost::shared_ptr< ::sensors::encoders > encodersPtr;
typedef boost::shared_ptr< ::sensors::encoders const> encodersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensors::encoders_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensors::encoders_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensors': ['/home/sti/Music/industryZone_pro/src/sensors/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensors::encoders_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensors::encoders_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensors::encoders_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::encoders_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensors::encoders_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensors::encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f714ae5c56b0e14e5ab0dffe4343917";
  }

  static const char* value(const ::sensors::encoders_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f714ae5c56b0e14ULL;
  static const uint64_t static_value2 = 0xe5ab0dffe4343917ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensors::encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensors/encoders";
  }

  static const char* value(const ::sensors::encoders_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensors::encoders_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 lfront\n\
float32 lrear\n\
float32 rfront\n\
float32 rrear\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::sensors::encoders_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensors::encoders_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lfront);
      stream.next(m.lrear);
      stream.next(m.rfront);
      stream.next(m.rrear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encoders_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensors::encoders_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensors::encoders_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lfront: ";
    Printer<float>::stream(s, indent + "  ", v.lfront);
    s << indent << "lrear: ";
    Printer<float>::stream(s, indent + "  ", v.lrear);
    s << indent << "rfront: ";
    Printer<float>::stream(s, indent + "  ", v.rfront);
    s << indent << "rrear: ";
    Printer<float>::stream(s, indent + "  ", v.rrear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSORS_MESSAGE_ENCODERS_H
